# Generated by Django 3.0.8 on 2020-07-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
