# Generated by Django 3.0.8 on 2020-07-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='input_image',
            field=models.ImageField(upload_to='<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
