# Generated by Django 3.0.8 on 2020-08-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200726_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='output_image_featureMap',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='userimages',
            name='output_image_gradcam',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='output_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
