# Generated by Django 3.0.8 on 2020-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200815_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='output_image_featureMap2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='userimages',
            name='output_image_gradcam2',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
