# Generated by Django 3.0.8 on 2020-08-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200815_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimages',
            name='output_image',
        ),
    ]
